#!/usr/bin/env python3
"""GEN-003: sync codec fixtures (fixtures/json/*.json) into the ArkTS test bundle.

The .json files under fixtures/json/ are the source of truth. Unit tests
cannot read files at runtime, so this script embeds them as string literals
in src/test/gen/FixtureData.ets. Run it after adding or editing a fixture:

    python3 core/td_api_generated/fixtures/sync_fixtures.py

The output is deterministic (fixtures sorted by file name).
"""
import json
import os
import sys

FIXTURES_DIR = os.path.dirname(os.path.abspath(__file__))
JSON_DIR = os.path.join(FIXTURES_DIR, "json")
OUT_PATH = os.path.join(FIXTURES_DIR, "..", "src", "test", "gen", "FixtureData.ets")

HEADER = """/**
 * GENERATED FILE - DO NOT EDIT.
 * Generated by fixtures/sync_fixtures.py (GEN-003) from fixtures/json/*.json.
 * Regenerate: python3 core/td_api_generated/fixtures/sync_fixtures.py
 */

export interface TdFixture {
  readonly name: string;
  readonly json: string;
}

"""


def main() -> int:
    names = sorted(
        n for n in os.listdir(JSON_DIR) if n.endswith(".json")
    )
    if not names:
        print("no fixtures found in", JSON_DIR, file=sys.stderr)
        return 1
    entries = []
    for file_name in names:
        path = os.path.join(JSON_DIR, file_name)
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
        # Validate: must be JSON with a string @type at top level.
        data = json.loads(text)
        if not isinstance(data, dict) or not isinstance(data.get("@type"), str):
            print("invalid fixture (missing top-level string @type):", path, file=sys.stderr)
            return 1
        name = file_name[: -len(".json")]
        # Compact form for the embedded literal; json.dumps escapes it into a
        # valid ArkTS/TS string literal.
        compact = json.dumps(data, ensure_ascii=True, separators=(",", ":"))
        entries.append((name, json.dumps(compact)))
    lines = [HEADER]
    lines.append("export const FIXTURES: TdFixture[] = [\n")
    for name, literal in entries:
        lines.append("  { name: %s, json: %s },\n" % (
            json.dumps(name), literal))
    lines.append("];\n")
    out = "".join(lines)
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(out)
    print("synced %d fixtures -> %s" % (len(entries), os.path.normpath(OUT_PATH)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
